server:
  port: 8091
spring:
  application:
    name: roubao-basics-orm
  datasource:
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/roubao
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 5000
      query-timeout: 100
      transaction-query-timeout: 100
      phy-timeout-millis: 10000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
