###
GET http://127.0.0.1:8090/logRecord/recordTest
Content-Type: application/json

###
POST http://127.0.0.1:8090/logRecord/customRecordTest
Content-Type: application/json

{
  "id": 999,
  "name": "roubao-test-customRecordTest"
}

###
POST http://127.0.0.1:8090/logRecord/customRecordTestAsync
Content-Type: application/json

{
  "id": 333,
  "name": "roubao-test-customRecordTest"
}